/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Arcademodel.gltf -o src/components/Arcademodel.jsx -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Arcademodel(props) {
  const { nodes, materials } = useGLTF('/models/Arcademodel.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Node-Mesh'].geometry} material={materials.mat14} />
      <mesh geometry={nodes['Node-Mesh_1'].geometry} material={materials.mat23} />
      <mesh geometry={nodes['Node-Mesh_2'].geometry} material={materials.mat22} />
      <mesh geometry={nodes['Node-Mesh_3'].geometry} material={materials.mat17} />
      <mesh geometry={nodes['Node-Mesh_4'].geometry} material={materials.mat13} />
      <mesh geometry={nodes['Node-Mesh_5'].geometry} material={materials.mat4} />
      <mesh geometry={nodes['Node-Mesh_6'].geometry} material={materials.mat10} />
      <mesh geometry={nodes['Node-Mesh_7'].geometry} material={materials.mat24} />
      <mesh geometry={nodes['Node-Mesh_8'].geometry} material={materials.mat21} />
      <mesh geometry={nodes['Node-Mesh_9'].geometry} material={materials.mat15} />
      <mesh geometry={nodes['Node-Mesh_10'].geometry} material={materials.mat8} />
      <mesh geometry={nodes['Node-Mesh_11'].geometry} material={materials.mat19} />
      <mesh geometry={nodes['Node-Mesh_12'].geometry} material={materials.mat20} />
      <mesh geometry={nodes['Node-Mesh_13'].geometry} material={materials.mat18} />
    </group>
  )
}

useGLTF.preload('/models/Arcademodel.gltf')
